name: Compile QEMU and Linux Kernel

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install QEMU Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglib2.0-dev libpixman-1-dev zlib1g-dev

    - name: Compile Linux Kernel 6.14
      run: |
        wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.14.tar.xz
        tar -xvf linux-6.14.tar.xz
        cd linux-6.14
        cp ../linux.config .config
        make oldconfig
        make -j$(nproc)
        sudo make modules_install install
        cd ..

    - name: Compile QEMU 9.2.3
      run: |
        wget https://download.qemu.org/qemu-9.2.3.tar.xz
        tar -xvf qemu-9.2.3.tar.xz
        cd qemu-9.2.3
        ./configure --target-list=x86_64-softmmu --disable-kvm --disable-vde
        make -j$(nproc)
        sudo make install
        cd ..
