name: Compile QEMU and Linux Kernel

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu

    - name: Set up Kernel Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libelf-dev libgelf-dev

    - name: Build the Kernel
      run: |
        make -C /path/to/linux-os
